# Polymorphism

## What is Polymorphism?

### Polymorphism, in simple terms, means 'many forms'. 


###  More specifically, polymorphism allows you to write code that can work with objects of different classes in a uniform way.


### This is achieved when different classes respond to the same method call in their own specific ways.


Polymorphism = "many forms".
It lets you use the same method name (or operator) across different classes, and the right behavior is chosen at runtime depending on the object.

In [ ]:
def speak():
    return "Woof!"

def speak():
    return "hii!"


speak()

In [33]:
class Dog:
    def speak(self):
        return "Woof!"


class Cat:
    def speak(self):
        return "Meow!"



# Polymorphism in action
animals = [Dog(), Cat()]
for a in animals:
    print(a.speak())  


# Woof!
# Meow!

Woof!
Meow!


## Without polymorphism (your current way)



In [34]:
# If multiple subclasses share the same method name but behave differently, polymorphism avoids if-else chains everywhere.

shape = "circle"
r = 5
w, h = 4, 6

if shape == "circle":
    area = 3.14 * r * r
elif shape == "rectangle":
    area = w * h

print("Area:", area)

Area: 78.5


## With polymorphism (your current way)

In [ ]:

class Circle:
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        return 3.14 * self.radius * self.radius


class Rectangle:
    
    def __init__(self, width, height):
        self.width = width
        self.height = height

    def area(self):
        return self.width * self.height


# Instead of checking `if shape == ...`
shapes = [Circle(5), Rectangle(4, 6)]

for s in shapes:
    print("Area:", s.area())


Area: 78.5
Area: 24


## Method overriding


Method overriding enables you to customize the behavior of inherited methods in subclasses to suit their specific needs.



Method overriding occurs when a subclass provides a specific implementation for a method that is already defined in its superclass. The subclass's method has the same name, parameters, and return type as the superclass's method.

When the method is called on an object of the subclass, the subclass's version of the method is executed, effectively 'overriding' the superclass's implementation. This is a key aspect of runtime polymorphism because the specific method that gets called is determined at runtime based on the object's actual type.


In [38]:
class Animal:

    def make_sound(self):
        print("Generic animal sound")

class Dog(Animal):
    
    def make_sound(self):
        print("Woof!")

    def call_sound(self):
        print
        self.make_sound()

animal=Animal()
dog=Dog()

animal.make_sound()
dog.make_sound()




Generic animal sound
Woof!


In [41]:
class Animal:
    def make_sound(self):
        print("Generic animal sound")

class Dog(Animal):
    def make_sound(self):
        print("Woof!")

    def call_sound(self):
        print
        self.make_sound()


class Cat(Animal):
    def make_sound(self):
      print("cattttttt")


animal = Animal()
dog = Dog()
cat=Cat()


animal.make_sound()
dog.call_sound()
cat.make_sound()



Generic animal sound
Woof!
cattttttt


In [ ]:
class Animal:
    def make_sound(self):
        print("Generic animal sound")

class Dog(Animal):
    
    def make_sound(self):
        print("Woof!")

    def call_sound(self):
        print
        self.make_sound()


class Cat(Animal):
    
    def make_sound(self):
        print("catttttt")

    def call_sound(self):
        print
        self.make_sound()


animal = Animal()
dog = Dog()
cat = Cat()


animal.make_sound()
dog.call_sound()
cat.call_sound()




Generic animal sound
Woof!
catttttt


# Duck Typing


Duck typing is a concept related to dynamic typing, where the type or class of an object is less important than the methods it defines. The name comes from the saying, \"If it walks like a duck and quacks like a duck, then it must be a duck.\"

In Python, duck typing means that you don't need to explicitly check the type of an object before calling its methods. Instead, you assume that if the object has the required methods, it will work correctly. If it doesn't, an exception will be raised at runtime.



In [ ]:

class Duck:
    def quack(self):
        print("Quack!")

class Person:
    def quack(self):
        print("The person imitates a duck.")



def make_quack(animal):
    animal.quack()           # calling method from class instance 


duck = Duck()
person = Person()

make_quack(duck)   # Output: Quack!
make_quack(person) # Output: The person imitates a duck.



Quack!
The person imitates a duck.


In this example, both `Duck` and `Person` have a `quack()` method. The `make_quack()` function doesn't care about the actual type of the object; it only cares that the object has a `quack()` method.

# What is Abstraction?

Abstraction simplifies complex systems. <br>
It allows you to focus on the essential aspects of an object.<br>
It promotes code reusability and maintainability.<br>

Q: How does abstraction help in managing complexity?

A: Abstraction helps manage complexity by hiding the intricate details of a system and presenting a simplified view. <br>
 This allows developers to work with high-level concepts without being overwhelmed by low-level implementation details. For example, when using a library, you don't need to know how the functions are implemented internally; you just need to know how to call them and what results to expect.

# Abstract Base Classes and Methods

### Abstract Base Classes (ABCs) are a way to define interfaces in Python. An abstract class cannot be instantiated directly; it serves as a blueprint for other classes.


## Instantiation means creating an object (instance) from a class.

from abc import ABC, abstractmethod

Imagine a car factory. The ABC is like the design specification that says every car *must* have a steering wheel and an engine.
Different car models (concrete classes) will implement these features in their own way, but they *must* have them to be considered a valid car.

Abstraction, in the context of object-oriented programming, is the process of hiding complex implementation details and 
exposing only the essential information about an object. It focuses on 'what' an object does rather than 'how' it does it.

<br>
 Think of it like driving a car. You need to know how to steer, accelerate, and brake (the 'what'),
but you don't need to understand the inner workings of the engine, transmission, or exhaust system (the 'how').

## WHY Abstract class


Abstract classes are used when you want to define a common blueprint for related classes, but you don’t want anyone to directly create objects from that blueprint.

## Using `abc` Module


The `abc` (Abstract Base Classes) module in Python provides the infrastructure for defining abstract base classes.<br> You use the `ABC` class as a base class for your abstract classes and the `@abstractmethod` decorator to declare abstract methods.

Provides tools for defining abstract base classes.
The `ABC` class is used as a base class.
The `@abstractmethod` decorator is used to declare abstract methods.

In engineering projects → A Sensor abstract class may define read_data(), and every specific sensor (TemperatureSensor, PressureSensor) implements it.

In UI frameworks → An abstract Widget may define draw(), and subclasses implement their own drawing logic.

In [ ]:
from abc import ABC, abstractmethod

class MyAbstractClass(ABC):
    
    @abstractmethod
    def my_abstract_method(self):
        pass

In [ ]:
from abc import ABC, abstractmethod

class Shape(ABC): #Abstract Base Class
    
    @abstractmethod
    def area(self):
        pass


class Square(Shape):
    def __init__(self, side):
        self.side = side

    

# shape = Shape()  # This will raise an error because Shape is abstract
square = Square(5)  # This will raise error as area() not implemented in child



TypeError: Can't instantiate abstract class Square with abstract method area

In [45]:

from abc import ABC, abstractmethod

class AbstractClass(ABC):
    def __init__(self):
        self.color = "Red Color"


    @abstractmethod
    def do_something(self):
        pass

class ConcreteClass(AbstractClass):

    def __init__(self):
        super().__init__()
        self.color = self.color
        print(self.color)


    def do_something(self):
        print("Doing something!")

# obj = AbstractClass()  # This will raise a TypeError: Can't instantiate abstract class
obj = ConcreteClass()
obj.do_something()


Red Color
Doing something!


Q: When should I use Abstract Base Classes?

A: Use ABCs when you want to define a common interface for a set of subclasses, enforce that subclasses implement certain methods, 
and prevent direct instantiation of the base class. They are particularly useful in large projects where consistency and maintainability are critical.

In [20]:
# Example showing , defining two abstractmethod

from abc import ABC, abstractmethod

class MyInterface(ABC):
    @abstractmethod
    def method1(self):
        pass

    @abstractmethod
    def method2(self):
        pass

class Implementation1(MyInterface):
    def method1(self):
        print("Implementation 1: Method 1")

    def method2(self):
        print("Implementation 1: Method 2")

In [46]:

# Abstraction Example, in multiple child class
from abc import ABC, abstractmethod

class Bank(ABC):
    @abstractmethod
    def get_interest_rate(self):
        pass

    # Not abstraced    
    def get_interest_rate2(self):
            pass


class HDFC(Bank):
    def get_interest_rate(self):
        return 7.5

class ICICI(Bank):
    def get_interest_rate(self):
        return 8.0

hdfc = HDFC()
icici = ICICI()

print("HDFC Interest Rate:", hdfc.get_interest_rate())
print("ICICI Interest Rate:", icici.get_interest_rate())

# The user only sees the get_interest_rate() method.
# The implementation details of how each bank calculates
# the interest rate are hidden (abstracted away).



HDFC Interest Rate: 7.5
ICICI Interest Rate: 8.0


In [ ]:

# Encapsulation Example
class Employee:
    def __init__(self, name, __salary):
        self.name = name
        self.__salary = __salary  # Private attribute

    def show(self):
        print("Name:", self.name)
        print("Salary:", self.__salary)

    def set_salary(self, amount):
      self.__salary = amount

emp = Employee("John", 50000)
emp.show()
# print(emp.__salary) # This will raise an AttributeError
emp.set_salary(60000) # proper way to change salary
emp.show()

# The salary attribute is "private" (using name mangling with __).
# It can only be accessed or modified through the class's methods
# (get_salary, set_salary), encapsulating the data and
# controlling access to it.


Name: John
Salary: 50000
Name: John
Salary: 60000


In [49]:
# Abstraction Example, in multiple child class
from abc import ABC, abstractmethod

class Bank(ABC):
    @abstractmethod
    def get_interest_rate(self):
        pass

    # Not abstraced    
    def get_interest_rate2(self):
            pass



class HDFC(Bank):
    def get_interest_rate(self):
        return 7.5



obj=HDFC()

# File Handling

File handling → Reading from and writing to files, allows persistent storage (data remains after program ends).

Opening files in Python → file = open('my_file.txt', 'w') (different modes: read, write, append, etc.).

Types of files:

Text files:

Store human-readable characters.

Encoded using ASCII or UTF-8(Unicode Transformation Format – 8-bit).

Examples: .txt, .csv, .html.

Uses 1 to 4 bytes per character:
English letters & numbers → 1 byte (same as ASCII).
Other characters (e.g., é, ह, 你, emojis 😀) → 2–4 bytes.


Can be opened with a text editor.

Binary files:

Store non-human-readable bytes.

Used for images, audio, video, executables.

Examples: .jpg, .exe, .zip.

Require specific programs to interpret.

ASCII (American Standard Code for Information Interchange) → An older character encoding that represents English letters, digits, and symbols using 7 bits (0–127 values). Example: A = 65.

UTF (Unicode Transformation Format) → A family of encodings (UTF-8, UTF-16, UTF-32) used to represent all characters in Unicode (languages, emojis, symbols). UTF-8 is most common and backward-compatible with ASCII.

# Opening and Closing Files

In [3]:
file = open('input_file.txt', 'r')   #('filename', 'mode')
file.close()

In [1]:
#Alternatively, the `with` statement provides a convenient way to automatically close files.
with open('input_file.txt', 'r') as file:
    content = file.read()
    print(content)
    print("----")

    

Hello World!
Hello second World!

14265B
----


# Modes

In [2]:
# 1. r (read) – Opens file for reading.
with open("input_file.txt", "r") as f:
    content = f.read()
    print(content)

Hello World!
Hello second World!

14265B


In [ ]:
# 1. r (read) – Opens file for reading.
with open("input_file.txt", "r") as f:
    content = f.readline()
    content = f.readline()
    content = f.readline() 
    print(content)

2. This is appended text.



In [3]:
# 1. r (read) – Opens file for reading.
with open("input_file.txt", "r") as f:
    content = f.readlines()
 
    print(content)

['1. Hello, World!\n', '2. This is appended text.\n', '3. This is appended text.']


In [3]:
# w (write) – Opens file for writing (overwrites if exists, else creates).

with open("input_file.txt", "w") as f:
    f.write("Hello, World!")   # old content erased

In [3]:

with open("input_devesh.txt", "w") as f:
    f.write("Hello, World!")   # old content erased

In [4]:
# a (append) – Opens file for writing at the end.
with open("input_file.txt", "a") as f:
    f.write("\nThis is appended text.")

In [1]:
# x (exclusive create) – Creates new file, fails if it already exists.

with open("new_file.txt", "x") as f:
    f.write("New file created!")

    

FileExistsError: [Errno 17] File exists: 'new_file.txt'

In [ ]:


with open("new_3.txt","x") as f:
    f.write("Newwwwwwww")



# 1. does file exist?
# 2. yes: ERROR
# 3. No, Create new file, write.




In [ ]:
# b (binary) – Used for binary files (combine with r/w).
with open("input_file.txt", "rb") as f:   # reading in binary
    data = f.read()
    print(data)


# When opened in binary mode, the file’s contents are read/written as raw bytes (b'\x68\x65\x6c\x6c\x6f' instead of "hello").
# Python will not decode the bytes into characters (like UTF-8 or ASCII).
# That means:
# You can still read text files in binary mode, but you’ll get bytes, not strings.
# To convert, you must decode manually:


b'Hello World!\r\nHello second World!'


In [ ]:
# t (text) – Default mode (combine with r/w).
with open("input_file.txt", "rt") as f:
    print(f.read())


# t (text mode) → Default mode for file handling.

# Reads/writes strings instead of raw bytes.

# Automatically handles encoding/decoding (default: UTF-8).

# Converts newlines (\n, \r\n) to the platform’s format.
                   

In [ ]:
# + (update: read + write) – Combine with other modes.
with open("input_file.txt", "r+") as f:
    content = f.read()
    f.write("\nAdded new line after reading.")


# + → Allows both reading and writing in the same file.
# Must be combined with another mode (r+, w+, a+).


In [4]:
file = open('input_file.txt', 'r') # File pointer at the beginning
content = file.read(5) # Reads 5 bytes, file pointer advances 5 bytes
print(content)

1. He


# The seek() Method

In [7]:
file = open('input_file.txt', 'r')
file.seek(10) # Moves the file pointer 10 bytes from the beginning
# file.seek(-5, 2) # Moves the file pointer 5 bytes from the end

content = file.read(5) # Reads 5 bytes, file pointer advances 5 bytes
print(content)

World


In [8]:

file.tell()

15

# The tell() Method

The `tell()` method returns the current position of the file pointer, measured in bytes from the beginning of the file. This is helpful for keeping track of your location within a file.

In [17]:
file = open('input_file.txt', 'r')
position = file.tell() # Returns 0 (at the beginning)`",`file.read(10)`,"`position = file.tell() # Returns 10 (after reading 10 bytes)
print(f"position:{position}")

position:0


# Packages

In [4]:

from Dir.pyDummy import *

res=add(5,7)
print(res)


12


In [2]:
from pyDummy import Sub,add

res=Sub(5,7)
print(res)


-2


In [ ]:
# Important note: Packages promote modularity, making your code more maintainable and scalable.

# The Python Package Index (PyPI)

In [ ]:
pip install numpy

# Virtula Env


python -m venv .venv

# Numpy: NumPy, short for Numerical Python,

NumPy's core is the `ndarray` object, which allows for storing and manipulating large amounts of numerical data. <br>
It provides significant performance advantages over standard Python lists, especially for numerical operations.  <br> 
NumPy's functions are vectorized, meaning they operate element-wise on arrays, leading to faster execution.  <br>

Vectorization: NumPy operations are vectorized, meaning they operate on entire arrays at once using optimized C code under the hood. This avoids explicit Python loops, which are slow. <br>
Data Type Homogeneity: NumPy arrays store elements of the same data type. This allows for more efficient storage and computation, as Python lists can contain mixed data types, requiring type checking for each operation. <br>
Contiguous Memory Allocation: NumPy arrays are stored in contiguous memory blocks, enabling fast access and efficient cache utilization. Python lists, on the other hand, store pointers to objects scattered in memory. <br>
Optimized Routines: NumPy provides highly optimized mathematical functions and linear algebra routines written in C and Fortran, leveraging hardware-specific optimizations. <br>

# NumPy Arrays (Creating, Indexing, Slicing)

`np.array()`: Creates an array from a list or tuple. 

example:` `arr = np.array([1, 2, 3, 4, 5])

In [5]:
lst=[1,2,3,4]

import numpy as np

arr=np.array(lst)

print(arr,type(arr))

[1 2 3 4] <class 'numpy.ndarray'>


In [6]:
import numpy as np

arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
import numpy as np

arr=np.zeros((5,5))  # 2x3 array of zeros
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
import numpy as np

arr=np.ones((5,2))  # 2x3 array of zeros
arr 

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
for i in range(50):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49


In [ ]:
# `np.arange()`: Creates an array with evenly spaced values within a given range.

import numpy as np
arr = np.arange(0, 10, 2)  #(array: [0, 2, 4, 6, 8])
arr



array([0, 2, 4, 6, 8])

In [14]:
for i in arr:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
# `np.linspace()`: Creates an array with evenly spaced values over a specified interval.
# `example:` `arr = np.linspace(0, 1, 5)` (array: [0. , 0.25, 0.5 , 0.75, 1. ])


arr = np.linspace(0, 1, 5) 
arr


# Use `np.linspace()` when you need to create an array of evenly spaced values over a specified interval, and you know the desired *number* of elements.

# Examples:

# Creating a smooth curve for plotting: Generate x-values for a mathematical function.
# Sampling data: Create evenly spaced time points for signal processing.
# Numerical integration: Define intervals for numerical methods.
# # Example: Creating 50 values from 0 to 1`
# `import numpy as np`
# `x = np.linspace(0, 1, 50)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [1]:
np.linspace(1,10,10)

NameError: name 'np' is not defined

In [1]:
ls1=[1,2,3]
ls2=ls1

ls2[0]=-5

print(ls2)
print(ls1)

[-5, 2, 3]
[-5, 2, 3]


In [ ]:
# Indexing: Accessing individual elements using their index (starting from 0).
import numpy as np
arr=np.array([1,2,3])
arr[0]
arr[:]




array([55,  2,  3])

In [ ]:
import numpy as np

# .copy()
arr=np.array([1,2,3])  #[1,2,3]
arr2=arr   # [1,2,3]
arr2[0]=55  # [55,2,3]


print(f"1. arr:{arr}") # array([55,  2,  3])
print(f"2. arr2:{arr2}") # array([55,  2,  3])



arr3=arr2.copy()
arr3[0]=66




print(f'2. arr2:{arr2}')
print(f'2. arr3:{arr3}')
#address
print(id(arr2),id(arr),id(arr3))


1. arr:[55  2  3]
2. arr2:[55  2  3]
2. arr2:[55  2  3]
2. arr3:[66  2  3]
3018184045072 3018184045072 3018184041424


In [3]:
# Array Attributes (Shape, Size, Dtype)
import numpy as np
arr=np.array([[1,2],
              [3,4],
              [5,6]])

print(f"arr.shape:{arr.shape}")   #Shape: A tuple indicating the dimensions of the array. For example, `(3, 4)` represents a 2D array with 3 rows and 4 columns.


print(f"arr.size:{arr.size}")    # Size: The total number of elements in the array.


# Dtype: The data type of the elements in the array (e.g., `int64`, `float64`, `object`). All elements in a NumPy array must have the same data type.

print(f"arr.dtype:{arr.dtype}")

# Ndim: Represents the number of dimensions (or axes) of the array.
print(f"arr.ndim:{arr.ndim}")



arr.shape:(3, 2)
arr.size:6
arr.dtype:int64
arr.ndim:2


In [44]:
# Important note: NumPy automatically infers the data type when creating an array, but you can explicitly specify it using the `dtype` argument.

## change the shape of a NumPy array

In [4]:
arr.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

# Basic Array Operations (Arithmetic, Comparison)

In [ ]:
'''

Arithmetic Operations:
Addition: `+` or `np.add()`
Subtraction: `-` or `np.subtract()`
Multiplication: `*` or `np.multiply()`
Division: `/` or `np.divide()`
Exponentiation: `**` or `np.power()`


'''


# example:` `arr1 + arr2` (element-wise addition)

'\nArithmetic Operations:\nAddition: `+` or `np.add()`\nSubtraction: `-` or `np.subtract()`\nMultiplication: `*` or `np.multiply()`\nDivision: `/` or `np.divide()`\nExponentiation: `**` or `np.power()`\n\n'

In [5]:
# Example 1: Adding two arrays

a = np.array([1, 2, 3])
b = np.array([4, 3, 6])

result1 = np.add(a, b)
print(f"add:{result1}")
print(np.power(a, b))
print(np.divide(a, b))

add:[5 5 9]
[  1   8 729]
[0.25       0.66666667 0.5       ]



# Trigonometric Functions:

In [ ]:
np.sin(np.array([0, np.pi/2, np.pi]))


array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [ ]:
np.exp(np.array([0, 1, 2]))
np.log(np.array([1, np.e, np.e**2]))


# Other Functions:
# `np.sqrt()`: Square root.
# `np.abs()`: Absolute value.
# `np.floor()`: Rounds down to the nearest integer.
# `np.ceil()`: Rounds up to the nearest integer.




array([0., 1., 2.])

In [ ]:
print(np.random.rand()) # Generates random numbers from a uniform distribution over [0, 1).
print(np.random.randn())  #: Generates random numbers from a standard normal distribution (mean 0, standard deviation 1).
print(np.random.randint(0, 10, size=(4, 4)))



0.8219738144952444
-0.7351659161317441
[[4 9 9 0]
 [0 5 4 5]
 [2 6 2 3]
 [8 7 3 4]]


In [10]:
import numpy as np
np.random.seed(8)
print(np.random.randint(0, 10))

3


In [ ]:
import random
random.seed(2)
print(random.randint(1,100))

8
