***Write a Program that reads a file from the end and prints its lines in reverse order (last line first , first line last ) without using readLines() or [::-1 Slicing]***

In [25]:
lines = []
reverse = []
with open("test1.txt","r") as f:
    for i in f:
        lines.append(i.strip())

    for j in range(len(lines)-1,-1,-1):
        reverse.append(lines[j])

print(reverse)


['Hello World I am a NotePadHello World I am a NotePad', 'Hello World I am a NotePad', 'Hello World I am a NotePad', 'Hello World I am a NotePad', 'Hello World I am a NotePad', 'Hello World I am a NotePad', 'Hello World I am a NotePad', '']


***2. Given a large text file , write a program that
    Read it in chunks of 100 characters each
    Create multiple smaller files(part1.txt, part2.txt)  containing those chunks. 
    Ensure the file pointer positions are managed correctly***

In [9]:
size = 10000
filenumber = 2
with open("../test1.txt","r") as f:
    while True:
        content = f.read(size)
        
        if not content : 
            break

        small_file_name = f"test{filenumber}.txt"
        with open(small_file_name,"w") as nf:
            nf.write(content)
        filenumber = filenumber + 1
            



3. Write a program that replaces all occurrences of the word "error" with "warning" 
inside a large log file without reading the entire file into memory at once.

In [26]:
#Input
with open("./test1.txt","r+") as f :
    content = f.readlines()
    print(content)

['Hello World I am a error\n', 'Hello World I am a Warning\n', 'Hello World I am a error\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello World I am a NotePad\n', 'Hello Worl

In [48]:
with open("./test1.txt","r+") as f , open("./temp.txt","w+") as temp:
    for i in f:
        temp.write(i.replace("error","warning"))
    f.seek(0)
    temp.seek(0)
    for j in temp:
        f.write(j)
    temp.seek(0)
    temp.truncate()


4. Create a Program that:
    1. Opens any Binary file(eg an image) in rb mode
    2. Reads the first 64bytes and prints themin hexidecimal format along with their file pointer positions(tell())
    3.Then jumps (seek()) to the last 32 bytes of the file and prints them too


In [61]:
with open("./R.jpg","rb") as img:
    for i in range(64):
        byte = img.read(1)
        print(f"Position{img.tell()} :{byte.hex()}")

Position1 :ff
Position2 :d8
Position3 :ff
Position4 :e0
Position5 :00
Position6 :10
Position7 :4a
Position8 :46
Position9 :49
Position10 :46
Position11 :00
Position12 :01
Position13 :01
Position14 :00
Position15 :00
Position16 :01
Position17 :00
Position18 :01
Position19 :00
Position20 :00
Position21 :ff
Position22 :fe
Position23 :00
Position24 :3b
Position25 :43
Position26 :52
Position27 :45
Position28 :41
Position29 :54
Position30 :4f
Position31 :52
Position32 :3a
Position33 :20
Position34 :67
Position35 :64
Position36 :2d
Position37 :6a
Position38 :70
Position39 :65
Position40 :67
Position41 :20
Position42 :76
Position43 :31
Position44 :2e
Position45 :30
Position46 :20
Position47 :28
Position48 :75
Position49 :73
Position50 :69
Position51 :6e
Position52 :67
Position53 :20
Position54 :49
Position55 :4a
Position56 :47
Position57 :20
Position58 :4a
Position59 :50
Position60 :45
Position61 :47
Position62 :20
Position63 :76
Position64 :36


12. A text file contains 100 integers separated by spaces. 
• Read the numbers into a NumPy array. 
• Reshape the array into 10x10. 
• Find the row with the maximum sum and print it

In [78]:
import numpy as np
with open("./12Question.txt","r") as data:
    numbers = data.read().split()
    numbers = [int(i) for i in numbers]
print(numbers)

data = np.array(numbers).reshape(10,10)
maxsum = 0
row =0
for i in range(10):
    if maxsum < data[i].sum():
        maxsum = data[i].sum()
        row = i

print(f"The maximum sum row is {data[row]} And sum of them is {maxsum}")

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
The maximum sum row is [ 91  92  93  94  95  96  97  98  99 100] And sum of them is 955


***11. Create a 7x7 matrix filled with ones. - Change the border elements to 0. - Change the 
center element to 9.***

In [86]:
x = np.ones((9,9))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [92]:
x[:,0]=0
x[0,:]=0
x[-1,:]=0
x[:,-1]=0
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [98]:
centre_row = x.shape[0]//2
centre_column = x.shape[1]//2
x[centre_row,centre_column]=9
centre_row , centre_column

(4, 4)

In [99]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 9., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

***9.Create two arrays: A = np.arange(1, 10).reshape(3,3) B = np.ones((3,3), dtype=int) * 5 - 
Perform element-wise addition, subtraction, multiplication, and division. - Compare A 
and B to return a Boolean mask of where elements of A are greater than B***

In [101]:
A = np.arange(1, 10).reshape(3,3)
B = np.ones((3,3), dtype=int) * 5
A,B

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]]))